CREATE DATABASE SoftUni;
GO
USE SoftUni

CREATE TABLE Towns(
Id INT PRIMARY KEY IDENTITY(1, 1),
[Name] NVARCHAR(50) NOT NULL
)
 
 CREATE TABLE Addresses(
 Id INT PRIMARY KEY IDENTITY(1,1),
 AddressText NVARCHAR(200) NOT NULL,
 TownId INT FOREIGN KEY REFERENCES Towns (Id)  Not null
 ) 
 CREATE TABLE Departments(
 Id INT PRIMARY KEY IDENTITY(1,1),
 [Name] VARCHAR(50) UNIQUE NOT NULL
 )

 CREATE TABLE Employees(
 Id Int PRIMARY KEY IDENTITY(1,1),
 FirstName VARCHAR(50) NOT NULL,
 MiddleName VARCHAR(50) NULL,
 LastName VARCHAR(80) NULL,
 JobTitle VARCHAR(100) NOT NULL,
 DepartmentId INT FOREIGN KEY REFERENCES Departments(Id) NOT NULL,
 HireDate DATE DEFAULT(GETDATE())NOT NULL,
 Salary DECIMAL (16,4) NOT NULL,
 AddressId INT FOREIGN KEY REFERENCES Addresses(Id) NOT NULL,

 )
